# Generated by Django 4.2.4 on 2023-08-16 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fechaproxima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fechaProxima', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Entregable',
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'ordering': ['apellido'], 'verbose_name': 'profesor', 'verbose_name_plural': 'profesores'},
        ),
    ]
