# Generated by Django 4.2.4 on 2023-08-17 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_fechaproxima_delete_entregable_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fechaproxima',
            options={'verbose_name': 'fecha proxima', 'verbose_name_plural': 'fechas proximas'},
        ),
    ]
